=== dhirajn72/allmylocalstuff/XMLTest1/src/student.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT jlc (student*,course+)>
<!ELEMENT student (sname+,email)>
<!ELEMENT course (cname+,date+,fee+)>
<!ELEMENT email (oemail,nemail)>
<!ELEMENT sname (#PCDATA)>
<!ELEMENT oemail (#PCDATA)>
<!ELEMENT nemail (#PCDATA)>
<!ELEMENT cname (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT fee (#PCDATA)>

<!ATTLIST student sid CDATA #REQUIRED>
<!ATTLIST course cid CDATA #REQUIRED>

<!ENTITY company "JLCCompany">

=== dhirajn72/allmylocalstuff/XMLTest1/src/student.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE jlc SYSTEM "student.dtd" >
<jlc>
  <student sid="">
    <sname>sname</sname>
    <email>
      <oemail>oemail</oemail>
      <nemail>nemail</nemail>
    </email>
  </student>
  <course cid="">
    <cname>cname</cname>
    <date>date</date>
    <fee>fee</fee>
  </course>
</jlc>
